import {
  Bot,
  Briefcase,
  Bitcoin,
  Code2,
  Compass,
  Gamepad2,
  Globe,
  GraduationCap,
  Handshake,
  HeartPulse,
  Home,
  ListChecks,
  MapPin,
  Megaphone,
  Mic,
  Newspaper,
  Palette,
  PenLine,
  Scale,
  Search,
  Share2,
  Shapes,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Target,
  Trophy,
  User,
  type LucideIcon,
} from "lucide-react";
import type { Category } from "@/lib/data";

export const CATEGORY_ICONS: Record<Category, LucideIcon> = {
  "AI Agents & Infrastructure": Bot,
  "SEO & AI Visibility": Search,
  "Marketing & Advertising": Megaphone,
  "Crypto, Web3 & Investing": Bitcoin,
  "Developer Tools": Code2,
  "Business, Finance & Legal": Scale,
  "Security, Privacy & Compliance": ShieldCheck,
  "Health, Fitness & Wellness": HeartPulse,
  "Social Media & Creator Tools": Share2,
  "Leaderboards & Attention Markets": Trophy,
  "Hiring, Jobs & Careers": Briefcase,
  "Education & Learning": GraduationCap,
  "Agencies, Studios & Services": Handshake,
  "Ecommerce & Retail": ShoppingCart,
  "Domains & Web Assets": Globe,
  "Games & Entertainment": Gamepad2,
  "People & Profiles": User,
  "Productivity & Personal Tools": ListChecks,
  "Design & Creative": Palette,
  "Writing & Content": PenLine,
  "Directories, Launch & Discovery": Compass,
  "AI Media Generation": Sparkles,
  "Audio, Voice & Podcasting": Mic,
  "Sales & Lead Generation": Target,
  "Travel, Local & Lifestyle": MapPin,
  "Real Estate & Property": Home,
  "Media & News": Newspaper,
  Other: Shapes,
};

// Short-label categories written by earlier seeds / claims
const LEGACY_CATEGORY_ICONS: Record<string, LucideIcon> = {
  Agents: Bot,
  SEO: Search,
  Marketing: Megaphone,
  Crypto: Bitcoin,
  Developer: Code2,
  Business: Scale,
  Security: ShieldCheck,
  Health: HeartPulse,
  Social: Share2,
  Leaderboards: Trophy,
  Hiring: Briefcase,
  Education: GraduationCap,
  Agencies: Handshake,
  Ecommerce: ShoppingCart,
  Domains: Globe,
  Games: Gamepad2,
  People: User,
  Productivity: ListChecks,
  Design: Palette,
  Writing: PenLine,
  Directories: Compass,
  "AI Media": Sparkles,
  Audio: Mic,
  Sales: Target,
  Travel: MapPin,
  "Real Estate": Home,
  Media: Newspaper,
  Other: Shapes,
};

// Safe resolver — never returns undefined, so rendering never crashes
export function resolveCategoryIcon(category: string): LucideIcon {
  return CATEGORY_ICONS[category as Category] ?? LEGACY_CATEGORY_ICONS[category] ?? Shapes;
}
